---
    name: Build Container Images
    
    on:
      workflow_call:
      workflow_dispatch:
    
    # Do not use concurrency to prevent simultaneous helm deployments
    jobs:
      build:
        name: Build Container Images
        runs-on: ubuntu-latest
        env:
          PHP_DOCKER_IMAGE: ghcr.io/kilip/crank-php:${{ github.sha }}
          PREFIX: ghcr.io/kilip/crank
        permissions:
          packages: "write"
          contents: "write"
        steps:
          - name: Checkout
            uses: actions/checkout@v4
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
    
          - name: Setup GHCR
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          
          - name: Get current date
            id: date
            run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
    
          - name: Build Docker images
            uses: docker/bake-action@v5
            with:
              # push and load may not be set together
              # must push manually in a next step
              pull: true
              load: true
              files: |
                compose.yaml
                compose.prod.yaml
              set: |
                *.cache-from=type=gha,scope=${{ github.ref }}
                *.cache-from=type=gha,scope=refs/heads/main
                *.cache-to=type=gha,scope=${{ github.ref }},mode=max
    
          - name: Docker push
            run: |
              docker push $PHP_DOCKER_IMAGE
    
          - name: Docker tag and push branch
            if: github.event_name != 'pull_request'
            run: |
              docker tag $PHP_DOCKER_IMAGE ${PREFIX}-php:${{ github.ref_name }}
              docker push ${PREFIX}-php:${{ github.ref_name }}
    
              docker tag $PHP_DOCKER_IMAGE ${PREFIX}-php:${{ github.ref_name }}-${{ steps.date.outputs.date }}
              docker push ${PREFIX}-php:${{ github.ref_name }}-${{ steps.date.outputs.date }}
